<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ExamTestOptional" tests="15" skipped="0" failures="1" errors="0" timestamp="2024-02-14T07:45:54" hostname="Random-2.local" time="0.025">
  <properties/>
  <testcase name="Latihan Opsional 1" classname="ExamTestOptional" time="0.006"/>
  <testcase name="Latihan Opsional 1" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 1" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 1" classname="ExamTestOptional" time="0.002"/>
  <testcase name="Latihan Opsional 2" classname="ExamTestOptional" time="0.001"/>
  <testcase name="Latihan Opsional 2" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 2" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 3" classname="ExamTestOptional" time="0.001"/>
  <testcase name="Latihan Opsional 3" classname="ExamTestOptional" time="0.008">
    <failure message="org.opentest4j.AssertionFailedError: Jika argumennya adalah 'dicoding0101' dan '60', fungsi manipulateString() seharusnya mengembalikkan nilai dicoding6060" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Jika argumennya adalah 'dicoding0101' dan '60', fungsi manipulateString() seharusnya mengembalikkan nilai dicoding6060
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at ExtentionsTestKt.assertEqualsWith(ExtentionsTest.kt:5)
	at ExamTestOptional$1$1$3$2.invoke(ExamTestOptional.kt:120)
	at ExamTestOptional$1$1$3$2.invoke(ExamTestOptional.kt:116)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
	at org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:84)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.spekframework.spek2.runtime.TaskRunner.runTask$lambda-2(executors.kt:26)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
</failure>
  </testcase>
  <testcase name="Latihan Opsional 4" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 4" classname="ExamTestOptional" time="0.001"/>
  <testcase name="Latihan Opsional 4" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 5" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 5" classname="ExamTestOptional" time="0.0"/>
  <testcase name="Latihan Opsional 5" classname="ExamTestOptional" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
